# Generated by Django 5.0.6 on 2024-05-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_role_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_restriction',
            field=models.BooleanField(default=False),
        ),
    ]
